name: sixam_mart_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.0.6
  connectivity_plus: ^5.0.2
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^1.0.7
  http: ^1.2.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  audioplayers: ^5.2.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.3.7
  phone_numbers_parser: ^8.1.0
  country_code_picker: ^3.0.0
  flutter_html: ^3.0.0-alpha.6
  bluetooth_thermal_printer: ^0.0.6
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  win32: ^5.2.0
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  flutter_pos_printer_platform: ^1.1.0
  esc_pos_utils: ^1.1.0
  screenshot: ^2.1.0
  http_parser: ^4.0.2
  path: ^1.8.1
  intl: ^0.18.0
  image: ^3.0.2
  dotted_border: ^2.0.0+1
  carousel_slider: ^4.0.0
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/food.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900